### ISSUE TITLE
Add HTML support for interpretation related fields

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#19]
HTML support for description, interpretations and comments in right side panel. 
Control bar should contain bold, italics, links and emoticons tools. No html clause is allowed. Ckeditor library (already integrated in DHIS2) will be reused and customised for this purpose.

**Comment by tokland** [comment]
Example:

![Screenshot from 2018-03-05 14-44-15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3783dd5b668ee1636555b424fa953444d04bea6d37ef5f22e7a98590cb9836f5d21943a11abb0821aeb05ba2088498ce0b58c5edcfa7f74b9dfd0126754505a9bf54f34a6934acd5af649e44a50a6143566e0647b.png)

I am not uploading it yet since there are problems with the emoticons on modal windows (since the smileys plugins tries to open a modal window itself). I'll see if there is a workaround.

**Comment by tokland** [comment]
- [ ] Use vendorScript for ./webpack.config.js (check maintenance-app)

**Comment by adrianq** [comment]
@tokland I think we can keep  the current behaviour re break lines i.e. enter will not submit the comment/interpretation

**Comment by tokland** [comment]
- [ ] PRs accepted, apply same to pivot-table, event-visualizer, events-report.

**Comment by tokland** [comment]
I'll wait for #21 before sending those PRs so we insert also the "reply" translation (before: "comment")

**Comment by tokland** [comment]
https://github.com/dhis2/charts-app/pull/46
https://github.com/dhis2/pivot-tables-app/pull/94
https://github.com/dhis2/event-reports-app/pull/17
https://github.com/dhis2/event-charts-app/pull/14
