### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-core#63]
See https://jira.dhis2.org/browse/DHIS2-5469

**Comment by tokland** [comment]
- [ ] Right-align date for interpretation and comment
- [ ] Date format for interpretations and comments: Nov 18, 2018 (make sure to observe locale)
- [ ] Comment time stamp should be just the date, no time, instead of i.e., "50 minutes ago"
- [ ] Comment should be put on separate line rather than inline with author's name

**Comment by tokland** [comment]
![Screenshot from 2019-01-14 10-51-14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f37a3dd4b768ee1236545e424fa853444d04bea6d37ef5f22e7a985959b880640c71c53e15a9bbd016bf00bc258b4682e5b98c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cf14fe44453a5103e60e3647b.png)

**Comment by tokland** [comment]
master: https://github.com/dhis2/d2-analysis/pull/84
v30: https://github.com/dhis2/d2-analysis/pull/85
